import type { VercelRequest, VercelResponse } from "@vercel/node";
import PDFDocument from "pdfkit";
import path from "path";
import fs from "fs";

// ── Brand colours ──────────────────────────────────────────────────────────
const TEAL = "#0D7377";
const MID_GREY = "#6b7280";
const DARK_TEXT = "#111827";
const BORDER = "#d1d5db";
const MARGIN = 50;
const PAGE_BOTTOM = 710; // safe bottom boundary (letter = 792pt)

// ── REGIONAL LANGUAGE SUPPORT ──────────────────────────────────────────────
// PDFKit's built-in Helvetica font only covers Latin characters.
// For Indian scripts (Devanagari, Bengali, Tamil, Telugu, Kannada, Malayalam,
// Gujarati), we use Noto Sans fonts from Google Fonts — open-source Unicode
// fonts that cover all these scripts perfectly.
//
// Font files are stored in api/fonts/ and bundled with the Vercel deployment.
// Total font bundle size: ~1.1MB (well within Vercel's 50MB function limit).
//
// Marathi uses the same Devanagari script as Hindi, so NotoSansDevanagari covers both.
//
// Font mapping: language code → Noto Sans TTF filename
const NOTO_FONT_MAP: Record<string, string> = {
  hi: "NotoSansDevanagari-Regular.ttf", // Hindi (Devanagari script)
  mr: "NotoSansDevanagari-Regular.ttf", // Marathi (also Devanagari)
  bn: "NotoSansBengali-Regular.ttf",    // Bengali
  ta: "NotoSansTamil-Regular.ttf",      // Tamil
  te: "NotoSansTelugu-Regular.ttf",     // Telugu
  kn: "NotoSansKannada-Regular.ttf",    // Kannada
  ml: "NotoSansMalayalam-Regular.ttf",  // Malayalam
  gu: "NotoSansGujarati-Regular.ttf",   // Gujarati
};

// Static label translations for the PDF's non-AI-generated text.
// These are the fixed labels that appear in the signature block and notice box.
// The AI generates the main content in the target language; these labels are
// hardcoded translations so the entire document is in the patient's language.
const LABELS: Record<string, {
  important: string;
  disclaimer: string;
  acknowledgement: string;
  confirmText: string;
  patientSignature: string;
  date: string;
  clinicianSignature: string;
  clinicianNameTitle: string;
  footerNote: string;
}> = {
  en: {
    important: "IMPORTANT:",
    disclaimer: "  This document is AI-assisted and must be reviewed by a licensed clinician before distribution.",
    acknowledgement: "ACKNOWLEDGEMENT",
    confirmText: "I confirm that I have received and understood these discharge instructions.",
    patientSignature: "Patient / Guardian Signature",
    date: "Date",
    clinicianSignature: "Clinician Signature",
    clinicianNameTitle: "Clinician Name & Title",
    footerNote: "Generated by MediFlow AI  •  AI-assisted document — must be reviewed by a licensed clinician before distribution.",
  },
  hi: {
    important: "महत्वपूर्ण:",
    disclaimer: "  यह दस्तावेज़ AI-सहायता से तैयार किया गया है और वितरण से पहले एक लाइसेंस प्राप्त चिकित्सक द्वारा समीक्षा की जानी चाहिए।",
    acknowledgement: "पावती",
    confirmText: "मैं पुष्टि करता/करती हूँ कि मुझे ये छुट्टी के निर्देश प्राप्त हुए हैं और मैंने इन्हें समझ लिया है।",
    patientSignature: "रोगी / अभिभावक के हस्ताक्षर",
    date: "तारीख",
    clinicianSignature: "चिकित्सक के हस्ताक्षर",
    clinicianNameTitle: "चिकित्सक का नाम और पद",
    footerNote: "MediFlow AI द्वारा तैयार  •  AI-सहायता प्राप्त दस्तावेज़ — वितरण से पहले लाइसेंस प्राप्त चिकित्सक द्वारा समीक्षा आवश्यक है।",
  },
  mr: {
    important: "महत्त्वाचे:",
    disclaimer: "  हे दस्तऐवज AI-सहाय्याने तयार केले आहे आणि वितरणापूर्वी परवानाधारक वैद्यकीय व्यावसायिकाने तपासणे आवश्यक आहे।",
    acknowledgement: "पोहोच",
    confirmText: "मी पुष्टी करतो/करते की मला हे डिस्चार्ज सूचना मिळाल्या आहेत आणि मला त्या समजल्या आहेत।",
    patientSignature: "रुग्ण / पालकाची सही",
    date: "तारीख",
    clinicianSignature: "वैद्यकीय व्यावसायिकाची सही",
    clinicianNameTitle: "वैद्यकीय व्यावसायिकाचे नाव आणि पद",
    footerNote: "MediFlow AI द्वारे तयार  •  AI-सहाय्यित दस्तऐवज — वितरणापूर्वी परवानाधारक वैद्यकीय व्यावसायिकाने तपासणे आवश्यक आहे।",
  },
  bn: {
    important: "গুরুত্বপূর্ণ:",
    disclaimer: "  এই নথিটি AI-সহায়তায় তৈরি এবং বিতরণের আগে একজন লাইসেন্সপ্রাপ্ত চিকিৎসক দ্বারা পর্যালোচনা করা আবশ্যক।",
    acknowledgement: "স্বীকৃতি",
    confirmText: "আমি নিশ্চিত করছি যে আমি এই ছাড়পত্রের নির্দেশনা পেয়েছি এবং বুঝেছি।",
    patientSignature: "রোগী / অভিভাবকের স্বাক্ষর",
    date: "তারিখ",
    clinicianSignature: "চিকিৎসকের স্বাক্ষর",
    clinicianNameTitle: "চিকিৎসকের নাম ও পদবি",
    footerNote: "MediFlow AI দ্বারা তৈরি  •  AI-সহায়তায় নথি — বিতরণের আগে লাইসেন্সপ্রাপ্ত চিকিৎসক দ্বারা পর্যালোচনা করা আবশ্যক।",
  },
  ta: {
    important: "முக்கியமான அறிவிப்பு:",
    disclaimer: "  இந்த ஆவணம் AI உதவியுடன் உருவாக்கப்பட்டது மற்றும் விநியோகிக்கும் முன் உரிமம் பெற்ற மருத்துவரால் மதிப்பாய்வு செய்யப்பட வேண்டும்.",
    acknowledgement: "ஒப்புகை",
    confirmText: "இந்த டிஸ்சார்ஜ் வழிமுறைகளை நான் பெற்று புரிந்துகொண்டதை உறுதிப்படுத்துகிறேன்.",
    patientSignature: "நோயாளி / பாதுகாவலர் கையொப்பம்",
    date: "தேதி",
    clinicianSignature: "மருத்துவர் கையொப்பம்",
    clinicianNameTitle: "மருத்துவர் பெயர் மற்றும் பட்டம்",
    footerNote: "MediFlow AI மூலம் உருவாக்கப்பட்டது  •  AI உதவி ஆவணம் — விநியோகிக்கும் முன் உரிமம் பெற்ற மருத்துவரால் மதிப்பாய்வு செய்யப்பட வேண்டும்.",
  },
  te: {
    important: "ముఖ్యమైన సమాచారం:",
    disclaimer: "  ఈ పత్రం AI సహాయంతో రూపొందించబడింది మరియు పంపిణీకి ముందు లైసెన్స్ పొందిన వైద్యుడు సమీక్షించాలి.",
    acknowledgement: "రసీదు",
    confirmText: "ఈ డిశ్చార్జ్ సూచనలను నేను అందుకున్నాను మరియు అర్థం చేసుకున్నాను అని నిర్ధారిస్తున్నాను.",
    patientSignature: "రోగి / సంరక్షకుడి సంతకం",
    date: "తేదీ",
    clinicianSignature: "వైద్యుడి సంతకం",
    clinicianNameTitle: "వైద్యుడి పేరు మరియు హోదా",
    footerNote: "MediFlow AI ద్వారా రూపొందించబడింది  •  AI సహాయ పత్రం — పంపిణీకి ముందు లైసెన్స్ పొందిన వైద్యుడు సమీక్షించాలి.",
  },
  kn: {
    important: "ಮಹತ್ವದ ಸೂಚನೆ:",
    disclaimer: "  ಈ ದಾಖಲೆಯನ್ನು AI ಸಹಾಯದಿಂದ ತಯಾರಿಸಲಾಗಿದೆ ಮತ್ತು ವಿತರಣೆಗೆ ಮೊದಲು ಪರವಾನಗಿ ಪಡೆದ ವೈದ್ಯರಿಂದ ಪರಿಶೀಲಿಸಬೇಕು.",
    acknowledgement: "ಸ್ವೀಕೃತಿ",
    confirmText: "ಈ ಡಿಸ್ಚಾರ್ಜ್ ಸೂಚನೆಗಳನ್ನು ನಾನು ಸ್ವೀಕರಿಸಿ ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತೇನೆ.",
    patientSignature: "ರೋಗಿ / ಪೋಷಕರ ಸಹಿ",
    date: "ದಿನಾಂಕ",
    clinicianSignature: "ವೈದ್ಯರ ಸಹಿ",
    clinicianNameTitle: "ವೈದ್ಯರ ಹೆಸರು ಮತ್ತು ಹುದ್ದೆ",
    footerNote: "MediFlow AI ಮೂಲಕ ರಚಿಸಲಾಗಿದೆ  •  AI ಸಹಾಯ ದಾಖಲೆ — ವಿತರಣೆಗೆ ಮೊದಲು ಪರವಾನಗಿ ಪಡೆದ ವೈದ್ಯರಿಂದ ಪರಿಶೀಲಿಸಬೇಕು.",
  },
  ml: {
    important: "പ്രധാന അറിയിപ്പ്:",
    disclaimer: "  ഈ രേഖ AI സഹായത്തോടെ തയ്യാറാക്കിയതാണ്, വിതരണത്തിന് മുമ്പ് ലൈസൻസ് ഉള്ള ഡോക്ടർ അവലോകനം ചെയ്യണം.",
    acknowledgement: "സ്വീകൃതി",
    confirmText: "ഈ ഡിസ്ചാർജ് നിർദ്ദേശങ്ങൾ ഞാൻ സ്വീകരിക്കുകയും മനസ്സിലാക്കുകയും ചെയ്തതായി ഞാൻ സ്ഥിരീകരിക്കുന്നു.",
    patientSignature: "രോഗി / രക്ഷകർത്താവിന്റെ ഒപ്പ്",
    date: "തീയതി",
    clinicianSignature: "ഡോക്ടറുടെ ഒപ്പ്",
    clinicianNameTitle: "ഡോക്ടറുടെ പേരും സ്ഥാനവും",
    footerNote: "MediFlow AI നിർമ്മിച്ചത്  •  AI സഹായ രേഖ — വിതരണത്തിന് മുമ്പ് ലൈസൻസ് ഉള്ള ഡോക്ടർ അവലോകനം ചെയ്യണം.",
  },
  gu: {
    important: "મહત્વપૂર્ણ:",
    disclaimer: "  આ દસ્તાવેજ AI-સહાયથી તૈયાર કરવામાં આવ્યો છે અને વિતરણ પહેલાં લાઇસન્સ ધારક ચિકિત્સક દ્વારા સમીક્ષા કરવી આવશ્યક છે.",
    acknowledgement: "પ્રાપ્તિ",
    confirmText: "હું પુષ્ટિ કરું છું કે મને આ ડિસ્ચાર્જ સૂચનાઓ મળી છે અને મેં તેને સમજ્યા છે.",
    patientSignature: "દર્દી / વાલીની સહી",
    date: "તારીખ",
    clinicianSignature: "ચિકિત્સકની સહી",
    clinicianNameTitle: "ચિકિત્સકનું નામ અને હોદ્દો",
    footerNote: "MediFlow AI દ્વારા તૈયાર  •  AI-સહાયિત દસ્તાવેજ — વિતરણ પહેલાં લાઇસન્સ ધારક ચિકિત્સક દ્વારા સમીક્ષા આવશ્યક છે.",
  },
};

// ── Helpers ────────────────────────────────────────────────────────────────

function drawWatermark(doc: InstanceType<typeof PDFDocument>) {
  doc.save();
  doc.opacity(0.055);
  doc.fontSize(68).fillColor(TEAL).font("Helvetica-Bold");
  const cx = doc.page.width / 2;
  const cy = doc.page.height / 2;
  doc.translate(cx, cy).rotate(-42).translate(-cx, -cy);
  doc.text("MediFlow AI", 0, cy - 34, { width: doc.page.width, align: "center" });
  doc.restore();
}

function drawFooter(doc: InstanceType<typeof PDFDocument>, footerNote: string) {
  const W = doc.page.width;
  const y = doc.page.height - 48;
  doc.moveTo(MARGIN, y).lineTo(W - MARGIN, y).strokeColor(BORDER).lineWidth(0.5).stroke();
  doc.fontSize(7).fillColor(MID_GREY).font("Helvetica");
  doc.text(footerNote, MARGIN, y + 8, { width: W - MARGIN * 2, align: "center" });
}

function drawHeader(
  doc: InstanceType<typeof PDFDocument>,
  patientName: string,
  patientAge: string,
  docDate: string,
  docId: string,
  docTitle: string,
  confidence?: number
): number {
  const W = doc.page.width;
  // Teal header bar — always in Latin/English (brand name stays in English)
  doc.rect(0, 0, W, 78).fill(TEAL);
  doc.fontSize(21).fillColor("white").font("Helvetica-Bold");
  doc.text("MediFlow AI", MARGIN, 20);
  doc.fontSize(8.5).fillColor("rgba(255,255,255,0.72)").font("Helvetica");
  doc.text("Clinical Workflow Automation", MARGIN, 46);
  doc.fontSize(10.5).fillColor("white").font("Helvetica-Bold");
  doc.text(docTitle.toUpperCase(), 0, 28, { width: W - MARGIN, align: "right" });

  // Patient info row
  doc.moveTo(MARGIN, 92).lineTo(W - MARGIN, 92).strokeColor(BORDER).lineWidth(0.5).stroke();
  doc.fontSize(13).fillColor(DARK_TEXT).font("Helvetica-Bold");
  doc.text(patientName, MARGIN, 100);
  doc.fontSize(8.5).fillColor(MID_GREY).font("Helvetica");
  const meta = [
    patientAge ? `Age/Sex: ${patientAge}` : null,
    `Date: ${docDate}`,
    `Case ID: ${docId}`,
    confidence != null ? `AI Confidence: ${confidence}%` : null,
  ].filter(Boolean).join("    |    ");
  doc.text(meta, MARGIN, 117);
  doc.moveTo(MARGIN, 133).lineTo(W - MARGIN, 133).strokeColor(BORDER).lineWidth(0.5).stroke();
  return 148;
}

// Check if we need a new page; if so, add one with watermark+footer
function checkPage(
  doc: InstanceType<typeof PDFDocument>,
  currentY: number,
  footerNote: string,
  needed = 30
): number {
  if (currentY + needed > PAGE_BOTTOM) {
    doc.addPage();
    drawWatermark(doc);
    drawFooter(doc, footerNote);
    return 60;
  }
  return currentY;
}

// Draw a teal-accented section heading, returns y after heading
function sectionHeading(
  doc: InstanceType<typeof PDFDocument>,
  title: string,
  y: number,
  bodyFont: string,
  footerNote: string
): number {
  y = checkPage(doc, y, footerNote, 40);
  const W = doc.page.width;
  doc.rect(MARGIN, y, 3, 15).fill(TEAL);
  // Use the body font for section headings so non-Latin scripts render correctly
  doc.fontSize(9.5).fillColor(TEAL).font(bodyFont);
  doc.text(title.toUpperCase(), MARGIN + 10, y + 1, { width: W - MARGIN * 2 - 10 });
  doc.moveTo(MARGIN + 10, y + 15).lineTo(W - MARGIN, y + 15).strokeColor(TEAL).lineWidth(0.35).stroke();
  return y + 24;
}

// Estimate height of a text block (approximate)
function estimateHeight(text: string, fontSize: number, maxWidth: number): number {
  const charsPerLine = Math.floor(maxWidth / (fontSize * 0.55));
  const lines = Math.ceil(text.length / charsPerLine) + 1;
  return lines * (fontSize + 3);
}

// Render a line with inline **bold** support, returns new y
// NOTE: For non-Latin scripts, bold is not available in Noto Sans Regular,
// so we use the same font for both bold and normal segments.
function renderInline(
  doc: InstanceType<typeof PDFDocument>,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  fontSize: number,
  color: string,
  bodyFont: string
): number {
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(p => p.length > 0);
  doc.fontSize(fontSize).fillColor(color);

  if (parts.length === 1) {
    doc.font(bodyFont);
    doc.text(text, x, y, { width: maxWidth });
    return doc.y;
  }

  // Mixed bold/normal — use bodyFont throughout (Noto fonts don't have separate bold)
  let isFirst = true;
  for (let i = 0; i < parts.length; i++) {
    const part = parts[i];
    const isBold = part.startsWith("**") && part.endsWith("**");
    const t = isBold ? part.slice(2, -2) : part;
    // For Latin (English), use Helvetica-Bold for bold segments
    // For non-Latin scripts, Noto Sans Regular handles all text
    doc.font(bodyFont === "Helvetica" && isBold ? "Helvetica-Bold" : bodyFont);
    const isLast = i === parts.length - 1;
    if (isFirst) {
      doc.text(t, x, y, { width: maxWidth, continued: !isLast });
      isFirst = false;
    } else {
      doc.text(t, { continued: !isLast });
    }
  }
  return doc.y;
}

// ── Main handler ───────────────────────────────────────────────────────────

export default function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const {
    content,
    patientName,
    patientAge,
    moduleLabel,
    caseId,
    confidence,
    generatedAt,
    language,  // ISO 639-1 language code: 'en', 'hi', 'bn', 'ta', 'te', 'kn', 'ml', 'mr', 'gu'
  } = req.body as {
    content: string;
    patientName?: string;
    patientAge?: string;
    moduleLabel?: string;
    moduleId?: string;
    caseId?: string;
    confidence?: number;
    generatedAt?: string;
    language?: string;
  };

  if (!content) return res.status(400).json({ error: "Missing content" });

  // ── FONT SELECTION ─────────────────────────────────────────────────────
  // Determine which font to use for body text based on the selected language.
  // English uses PDFKit's built-in Helvetica (no file needed).
  // All Indian scripts use the corresponding Noto Sans TTF from api/fonts/.
  const lang = language && language !== "en" ? language : "en";
  const labels = LABELS[lang] ?? LABELS.en;

  // Register the appropriate Noto Sans font for non-English languages
  let bodyFont = "Helvetica";
  let fontRegistered = false;

  const docForFont = null; // will register after doc creation

  const docDate = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const docId = caseId || `MF-${Date.now().toString(36).toUpperCase()}`;
  const safePatientName = patientName || "Patient";
  const docTitle = moduleLabel || "Clinical Report";
  const W = 612;
  const contentWidth = W - MARGIN * 2;

  const doc = new PDFDocument({
    size: "LETTER",
    margin: 0,
    autoFirstPage: true,
    info: {
      Title: `${docTitle} — ${safePatientName}`,
      Author: "MediFlow AI",
      Subject: docTitle,
      Creator: "MediFlow AI Clinical Workflow Platform",
    },
  });

  // Register Noto Sans font for the selected language after doc creation
  if (lang !== "en" && NOTO_FONT_MAP[lang]) {
    const fontFileName = NOTO_FONT_MAP[lang];
    // __dirname resolves to the api/ directory in both local dev and Vercel deployment
    const fontPath = path.join(__dirname, "fonts", fontFileName);
    if (fs.existsSync(fontPath)) {
      const fontName = `NotoSans-${lang}`;
      doc.registerFont(fontName, fontPath);
      bodyFont = fontName;
      fontRegistered = true;
    }
    // If font file not found, fall back to Helvetica (Latin characters only)
    // This is a graceful degradation — the PDF will still generate, just without
    // proper script rendering. This should not happen in production.
  }

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const pdfPromise = new Promise<void>((resolve) => {
    doc.on("end", resolve);

    // ── Page 1 setup ─────────────────────────────────────────────────────
    drawWatermark(doc);
    drawFooter(doc, labels.footerNote);
    let y = drawHeader(doc, safePatientName, patientAge || "", docDate, docId, docTitle, confidence);

    // ── Important notice box ─────────────────────────────────────────────
    doc.rect(MARGIN, y, contentWidth, 30).fill("#fef3c7");
    doc.rect(MARGIN, y, 3, 30).fill("#f59e0b");
    doc.fontSize(8).fillColor("#92400e").font(bodyFont);
    doc.text(labels.important, MARGIN + 10, y + 5, { width: contentWidth - 16, lineBreak: false });
    doc.text(labels.disclaimer, { width: contentWidth - 16 });
    y += 40;

    // ── Parse and render content line by line ────────────────────────────
    const lines = content.split("\n");

    for (const rawLine of lines) {
      const line = rawLine.trimEnd();

      // Blank line → small gap
      if (!line.trim()) {
        y += 4;
        continue;
      }

      // Section heading: entire line is **text** (optionally ending with colon)
      const onlyBold = /^\*\*([^*]+)\*\*\s*:?\s*$/.test(line.trim());
      if (onlyBold) {
        const headText = line.trim().replace(/^\*\*/, "").replace(/\*\*\s*:?\s*$/, "");
        y += 6;
        y = sectionHeading(doc, headText, y, bodyFont, labels.footerNote);
        continue;
      }

      y = checkPage(doc, y, labels.footerNote, 22);

      // Bullet point (- or •)
      if (/^[-•]\s+/.test(line)) {
        const body = line.replace(/^[-•]\s+/, "");
        const est = estimateHeight(body, 9, contentWidth - 16);
        y = checkPage(doc, y, labels.footerNote, est);
        doc.fontSize(9).fillColor(DARK_TEXT).font(bodyFont);
        doc.text("•", MARGIN + 4, y, { width: 10, lineBreak: false });
        y = renderInline(doc, body, MARGIN + 16, y, contentWidth - 16, 9, DARK_TEXT, bodyFont);
        y += 2;
        continue;
      }

      // Numbered list item
      const numMatch = line.match(/^(\d+)\.\s+(.*)$/);
      if (numMatch) {
        const est = estimateHeight(numMatch[2], 9, contentWidth - 22);
        y = checkPage(doc, y, labels.footerNote, est);
        doc.fontSize(9).fillColor(DARK_TEXT).font(bodyFont);
        doc.text(numMatch[1] + ".", MARGIN + 4, y, { width: 18, lineBreak: false });
        y = renderInline(doc, numMatch[2], MARGIN + 22, y, contentWidth - 22, 9, DARK_TEXT, bodyFont);
        y += 2;
        continue;
      }

      // Regular paragraph / inline bold line
      const est = estimateHeight(line, 9, contentWidth - 8);
      y = checkPage(doc, y, labels.footerNote, est);
      y = renderInline(doc, line, MARGIN + 8, y, contentWidth - 8, 9, DARK_TEXT, bodyFont);
      y += 2;
    }

    // ── Signature block (only for discharge module) ───────────────────────
    const isDischarge = docTitle.toLowerCase().includes("discharge");
    if (isDischarge) {
      y = checkPage(doc, y, labels.footerNote, 130);
      y += 18;
      doc.moveTo(MARGIN, y).lineTo(W - MARGIN, y).strokeColor(BORDER).lineWidth(0.5).stroke();
      y += 12;

      doc.fontSize(9).fillColor(DARK_TEXT).font(bodyFont);
      doc.text(labels.acknowledgement, MARGIN, y, { width: contentWidth });
      y += 13;
      doc.fontSize(8.5).fillColor(MID_GREY).font(bodyFont);
      doc.text(labels.confirmText, MARGIN, y, { width: contentWidth });
      y += 22;

      doc.moveTo(MARGIN, y + 18).lineTo(MARGIN + 200, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.fontSize(7.5).fillColor(MID_GREY).font(bodyFont);
      doc.text(labels.patientSignature, MARGIN, y + 22);
      doc.moveTo(W - MARGIN - 140, y + 18).lineTo(W - MARGIN, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.text(labels.date, W - MARGIN - 140, y + 22);

      y += 45;
      doc.moveTo(MARGIN, y + 18).lineTo(MARGIN + 200, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.text(labels.clinicianSignature, MARGIN, y + 22);
      doc.moveTo(W - MARGIN - 200, y + 18).lineTo(W - MARGIN, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.text(labels.clinicianNameTitle, W - MARGIN - 200, y + 22);
    }

    doc.end();
  });

  return pdfPromise.then(() => {
    const pdfBuffer = Buffer.concat(chunks);
    const safeName = safePatientName.replace(/\s+/g, "-").toLowerCase();
    const filename = `mediflow-${docTitle.toLowerCase().replace(/\s+/g, "-")}-${safeName}-${docId}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", pdfBuffer.length);
    return res.status(200).send(pdfBuffer);
  });
}
