import type { VercelRequest, VercelResponse } from "@vercel/node";
import PDFDocument from "pdfkit";

// ── Brand colours ──────────────────────────────────────────────────────────
const TEAL = "#0D7377";
const MID_GREY = "#6b7280";
const DARK_TEXT = "#111827";
const BORDER = "#d1d5db";
const MARGIN = 50;
const PAGE_BOTTOM = 710; // safe bottom boundary (letter = 792pt)

// ── Helpers ────────────────────────────────────────────────────────────────

function drawWatermark(doc: InstanceType<typeof PDFDocument>) {
  doc.save();
  doc.opacity(0.055);
  doc.fontSize(68).fillColor(TEAL).font("Helvetica-Bold");
  const cx = doc.page.width / 2;
  const cy = doc.page.height / 2;
  doc.translate(cx, cy).rotate(-42).translate(-cx, -cy);
  doc.text("MediFlow AI", 0, cy - 34, { width: doc.page.width, align: "center" });
  doc.restore();
}

function drawFooter(doc: InstanceType<typeof PDFDocument>) {
  const W = doc.page.width;
  const y = doc.page.height - 48;
  doc.moveTo(MARGIN, y).lineTo(W - MARGIN, y).strokeColor(BORDER).lineWidth(0.5).stroke();
  doc.fontSize(7).fillColor(MID_GREY).font("Helvetica");
  doc.text(
    "Generated by MediFlow AI  •  AI-assisted document — must be reviewed by a licensed clinician before distribution.",
    MARGIN, y + 8, { width: W - MARGIN * 2, align: "center" }
  );
}

function drawHeader(
  doc: InstanceType<typeof PDFDocument>,
  patientName: string,
  patientAge: string,
  docDate: string,
  docId: string,
  docTitle: string,
  confidence?: number
): number {
  const W = doc.page.width;
  // Teal header bar
  doc.rect(0, 0, W, 78).fill(TEAL);
  doc.fontSize(21).fillColor("white").font("Helvetica-Bold");
  doc.text("MediFlow AI", MARGIN, 20);
  doc.fontSize(8.5).fillColor("rgba(255,255,255,0.72)").font("Helvetica");
  doc.text("Clinical Workflow Automation", MARGIN, 46);
  doc.fontSize(10.5).fillColor("white").font("Helvetica-Bold");
  doc.text(docTitle.toUpperCase(), 0, 28, { width: W - MARGIN, align: "right" });

  // Patient info row
  doc.moveTo(MARGIN, 92).lineTo(W - MARGIN, 92).strokeColor(BORDER).lineWidth(0.5).stroke();
  doc.fontSize(13).fillColor(DARK_TEXT).font("Helvetica-Bold");
  doc.text(patientName, MARGIN, 100);
  doc.fontSize(8.5).fillColor(MID_GREY).font("Helvetica");
  const meta = [
    patientAge ? `Age/Sex: ${patientAge}` : null,
    `Date: ${docDate}`,
    `Case ID: ${docId}`,
    confidence != null ? `AI Confidence: ${confidence}%` : null,
  ].filter(Boolean).join("    |    ");
  doc.text(meta, MARGIN, 117);
  doc.moveTo(MARGIN, 133).lineTo(W - MARGIN, 133).strokeColor(BORDER).lineWidth(0.5).stroke();
  // Return the y position where content should start
  return 148;
}

// Check if we need a new page; if so, add one with watermark+footer
function checkPage(doc: InstanceType<typeof PDFDocument>, currentY: number, needed = 30): number {
  if (currentY + needed > PAGE_BOTTOM) {
    doc.addPage();
    drawWatermark(doc);
    drawFooter(doc);
    return 60;
  }
  return currentY;
}

// Draw a teal-accented section heading, returns y after heading
function sectionHeading(doc: InstanceType<typeof PDFDocument>, title: string, y: number): number {
  y = checkPage(doc, y, 40);
  const W = doc.page.width;
  doc.rect(MARGIN, y, 3, 15).fill(TEAL);
  doc.fontSize(9.5).fillColor(TEAL).font("Helvetica-Bold");
  doc.text(title.toUpperCase(), MARGIN + 10, y + 1, { width: W - MARGIN * 2 - 10 });
  doc.moveTo(MARGIN + 10, y + 15).lineTo(W - MARGIN, y + 15).strokeColor(TEAL).lineWidth(0.35).stroke();
  return y + 24;
}

// Estimate height of a text block (approximate)
function estimateHeight(text: string, fontSize: number, maxWidth: number): number {
  const charsPerLine = Math.floor(maxWidth / (fontSize * 0.55));
  const lines = Math.ceil(text.length / charsPerLine) + 1;
  return lines * (fontSize + 3);
}

// Render a line with inline **bold** support, returns new y
function renderInline(
  doc: InstanceType<typeof PDFDocument>,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  fontSize: number,
  color: string
): number {
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(p => p.length > 0);
  doc.fontSize(fontSize).fillColor(color);

  if (parts.length === 1) {
    doc.font("Helvetica");
    doc.text(text, x, y, { width: maxWidth });
    return doc.y;
  }

  // Mixed bold/normal
  let isFirst = true;
  for (let i = 0; i < parts.length; i++) {
    const part = parts[i];
    const isBold = part.startsWith("**") && part.endsWith("**");
    const t = isBold ? part.slice(2, -2) : part;
    doc.font(isBold ? "Helvetica-Bold" : "Helvetica");
    const isLast = i === parts.length - 1;
    if (isFirst) {
      doc.text(t, x, y, { width: maxWidth, continued: !isLast });
      isFirst = false;
    } else {
      doc.text(t, { continued: !isLast });
    }
  }
  return doc.y;
}

// ── Main handler ───────────────────────────────────────────────────────────

export default function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const {
    content,
    patientName,
    patientAge,
    moduleLabel,
    caseId,
    confidence,
    generatedAt,
  } = req.body as {
    content: string;
    patientName?: string;
    patientAge?: string;
    moduleLabel?: string;
    moduleId?: string;
    caseId?: string;
    confidence?: number;
    generatedAt?: string;
  };

  if (!content) return res.status(400).json({ error: "Missing content" });

  const docDate = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const docId = caseId || `MF-${Date.now().toString(36).toUpperCase()}`;
  const safePatientName = patientName || "Patient";
  const docTitle = moduleLabel || "Clinical Report";
  const W = 612;
  const contentWidth = W - MARGIN * 2;

  // Use no auto-margins so we control all positioning manually
  const doc = new PDFDocument({
    size: "LETTER",
    margin: 0,
    autoFirstPage: true,
    info: {
      Title: `${docTitle} — ${safePatientName}`,
      Author: "MediFlow AI",
      Subject: docTitle,
      Creator: "MediFlow AI Clinical Workflow Platform",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const pdfPromise = new Promise<void>((resolve) => {
    doc.on("end", resolve);

    // ── Page 1 setup ─────────────────────────────────────────────────────
    drawWatermark(doc);
    drawFooter(doc);
    let y = drawHeader(doc, safePatientName, patientAge || "", docDate, docId, docTitle, confidence);

    // ── Important notice box ─────────────────────────────────────────────
    doc.rect(MARGIN, y, contentWidth, 30).fill("#fef3c7");
    doc.rect(MARGIN, y, 3, 30).fill("#f59e0b");
    doc.fontSize(8).fillColor("#92400e").font("Helvetica-Bold");
    doc.text("IMPORTANT:", MARGIN + 10, y + 5, { width: contentWidth - 16, lineBreak: false });
    doc.font("Helvetica");
    doc.text(
      "  This document is AI-assisted and must be reviewed by a licensed clinician before distribution.",
      { width: contentWidth - 16 }
    );
    y += 40;

    // ── Parse and render content line by line ────────────────────────────
    const lines = content.split("\n");

    for (const rawLine of lines) {
      const line = rawLine.trimEnd();

      // Blank line → small gap
      if (!line.trim()) {
        y += 4;
        continue;
      }

      // Section heading: entire line is **text** (optionally ending with colon)
      const onlyBold = /^\*\*([^*]+)\*\*\s*:?\s*$/.test(line.trim());
      if (onlyBold) {
        const headText = line.trim().replace(/^\*\*/, "").replace(/\*\*\s*:?\s*$/, "");
        y += 6;
        y = sectionHeading(doc, headText, y);
        continue;
      }

      y = checkPage(doc, y, 22);

      // Bullet point (- or •)
      if (/^[-•]\s+/.test(line)) {
        const body = line.replace(/^[-•]\s+/, "");
        const est = estimateHeight(body, 9, contentWidth - 16);
        y = checkPage(doc, y, est);
        doc.fontSize(9).fillColor(DARK_TEXT).font("Helvetica");
        doc.text("•", MARGIN + 4, y, { width: 10, lineBreak: false });
        y = renderInline(doc, body, MARGIN + 16, y, contentWidth - 16, 9, DARK_TEXT);
        y += 2;
        continue;
      }

      // Numbered list item
      const numMatch = line.match(/^(\d+)\.\s+(.*)$/);
      if (numMatch) {
        const est = estimateHeight(numMatch[2], 9, contentWidth - 22);
        y = checkPage(doc, y, est);
        doc.fontSize(9).fillColor(DARK_TEXT).font("Helvetica-Bold");
        doc.text(numMatch[1] + ".", MARGIN + 4, y, { width: 18, lineBreak: false });
        y = renderInline(doc, numMatch[2], MARGIN + 22, y, contentWidth - 22, 9, DARK_TEXT);
        y += 2;
        continue;
      }

      // Regular paragraph / inline bold line
      const est = estimateHeight(line, 9, contentWidth - 8);
      y = checkPage(doc, y, est);
      y = renderInline(doc, line, MARGIN + 8, y, contentWidth - 8, 9, DARK_TEXT);
      y += 2;
    }

    // ── Signature block (only for discharge module) ───────────────────────
    const isDischarge = docTitle.toLowerCase().includes("discharge");
    if (isDischarge) {
      y = checkPage(doc, y, 130);
      y += 18;
      doc.moveTo(MARGIN, y).lineTo(W - MARGIN, y).strokeColor(BORDER).lineWidth(0.5).stroke();
      y += 12;

      doc.fontSize(9).fillColor(DARK_TEXT).font("Helvetica-Bold");
      doc.text("ACKNOWLEDGEMENT", MARGIN, y, { width: contentWidth });
      y += 13;
      doc.fontSize(8.5).fillColor(MID_GREY).font("Helvetica");
      doc.text(
        "I confirm that I have received and understood these discharge instructions.",
        MARGIN, y, { width: contentWidth }
      );
      y += 22;

      doc.moveTo(MARGIN, y + 18).lineTo(MARGIN + 200, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.fontSize(7.5).fillColor(MID_GREY).font("Helvetica");
      doc.text("Patient / Guardian Signature", MARGIN, y + 22);
      doc.moveTo(W - MARGIN - 140, y + 18).lineTo(W - MARGIN, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.text("Date", W - MARGIN - 140, y + 22);

      y += 45;
      doc.moveTo(MARGIN, y + 18).lineTo(MARGIN + 200, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.text("Clinician Signature", MARGIN, y + 22);
      doc.moveTo(W - MARGIN - 200, y + 18).lineTo(W - MARGIN, y + 18).strokeColor(DARK_TEXT).lineWidth(0.5).stroke();
      doc.text("Clinician Name & Title", W - MARGIN - 200, y + 22);
    }

    doc.end();
  });

  return pdfPromise.then(() => {
    const pdfBuffer = Buffer.concat(chunks);
    const safeName = safePatientName.replace(/\s+/g, "-").toLowerCase();
    const filename = `mediflow-${docTitle.toLowerCase().replace(/\s+/g, "-")}-${safeName}-${docId}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", pdfBuffer.length);
    return res.status(200).send(pdfBuffer);
  });
}
