import type { VercelRequest, VercelResponse } from "@vercel/node";
// @ts-ignore
import PDFDocument from "pdfkit";

// ── Brand colours ──────────────────────────────────────────────────────────
const TEAL       = "#0D7377";
const TEAL_DARK  = "#0a5c60";
const CORAL      = "#e05a4e";
const MID_GREY   = "#6b7280";
const DARK_TEXT  = "#111827";
const BORDER     = "#d1d5db";
const ROW_ALT    = "#f9fafb";
const MARGIN     = 45;
const PAGE_BOTTOM = 720;

// ── Helpers ────────────────────────────────────────────────────────────────

/** Strip markdown, HTML tags, extra whitespace from any field value */
function clean(val: string | undefined | null): string {
  if (!val) return "";
  return val
    .replace(/<[^>]+>/g, "")
    .replace(/\*\*/g, "")
    .replace(/[*_`#]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Extract just the drug name from a string that may contain strength/form appended.
 * e.g. "Amoxicillin 500mg Capsule" → "Amoxicillin"
 *      "Metformin HCl 850 MG Tablet" → "Metformin HCl"
 *      "Ibuprofen (200mg)" → "Ibuprofen"
 */
function extractDrugName(raw: string): string {
  const s = clean(raw);
  if (!s) return "";
  // Remove anything after a dose number pattern: digits followed by mg/mcg/ml/g/iu/units/%
  const stripped = s
    .replace(/\s*\(.*?\)/g, "")                          // remove parenthetical e.g. (500mg)
    .replace(/\s+\d+[\d.,]*\s*(mg|mcg|ml|g|iu|units|%|mmol|mEq|meq)\b.*/i, "") // "500mg ..."
    .replace(/\s+\d+[\d.,]*\s*(tablet|capsule|cap|tab|syrup|cream|gel|drop|patch|inhaler|injection|solution|suspension|ointment|spray|lozenge|suppository|powder|sachet|vial|ampoule|ampule)\b.*/i, "")
    .replace(/\s+(tablet|capsule|cap|tab|syrup|cream|gel|drop|patch|inhaler|injection|solution|suspension|ointment|spray|lozenge|suppository|powder|sachet|vial|ampoule|ampule)s?\b.*/i, "")
    .trim();
  return stripped || s;
}

function drawWatermark(doc: InstanceType<typeof PDFDocument>) {
  doc.save();
  doc.opacity(0.04);
  doc.fontSize(72).fillColor(TEAL).font("Helvetica-Bold");
  const cx = doc.page.width / 2;
  const cy = doc.page.height / 2;
  doc.translate(cx, cy).rotate(-42).translate(-cx, -cy);
  doc.text("MediFlow AI", 0, cy - 36, { width: doc.page.width, align: "center" });
  doc.restore();
}

function drawFooter(doc: InstanceType<typeof PDFDocument>, docId: string) {
  const W = doc.page.width;
  const y = doc.page.height - 44;
  doc.moveTo(MARGIN, y).lineTo(W - MARGIN, y).strokeColor(BORDER).lineWidth(0.4).stroke();
  doc.fontSize(6.5).fillColor(MID_GREY).font("Helvetica");
  doc.text(
    `Case ID: ${docId}  •  Generated by MediFlow AI  •  CONFIDENTIAL — For patient use only. Verify with a licensed pharmacist before dispensing.`,
    MARGIN, y + 8, { width: W - MARGIN * 2, align: "center" }
  );
}

function drawHeader(
  doc: InstanceType<typeof PDFDocument>,
  patientName: string,
  prescribingDoctor: string,
  docDate: string,
  docId: string,
  clinicName: string
): number {
  const W = doc.page.width;
  doc.rect(0, 0, W, 72).fill(TEAL);
  doc.fontSize(20).fillColor("white").font("Helvetica-Bold");
  doc.text("MediFlow AI", MARGIN, 18);
  doc.fontSize(8).fillColor("rgba(255,255,255,0.7)").font("Helvetica");
  doc.text("Clinical Workflow Automation", MARGIN, 42);
  doc.fontSize(10).fillColor("white").font("Helvetica-Bold");
  doc.text("MEDICATION PRESCRIPTION RECORD", 0, 26, { width: W - MARGIN, align: "right" });

  doc.rect(0, 72, W, 22).fill(TEAL_DARK);
  doc.fontSize(7.5).fillColor("rgba(255,255,255,0.85)").font("Helvetica");
  doc.text(`Case ID: ${docId}`, MARGIN, 79, { lineBreak: false });
  doc.text(`Generated: ${docDate}`, 0, 79, { width: W - MARGIN, align: "right" });

  let y = 108;
  doc.fontSize(14).fillColor(DARK_TEXT).font("Helvetica-Bold");
  doc.text(patientName, MARGIN, y);
  y = doc.y + 3;

  const meta: string[] = [];
  if (prescribingDoctor) meta.push(`Prescribing Doctor: ${prescribingDoctor}`);
  if (clinicName) meta.push(`Clinic: ${clinicName}`);
  if (meta.length > 0) {
    doc.fontSize(8.5).fillColor(MID_GREY).font("Helvetica");
    doc.text(meta.join("    |    "), MARGIN, y);
    y = doc.y + 4;
  }
  doc.moveTo(MARGIN, y + 2).lineTo(W - MARGIN, y + 2).strokeColor(BORDER).lineWidth(0.5).stroke();
  return y + 14;
}

function checkPage(doc: InstanceType<typeof PDFDocument>, y: number, needed: number, docId: string): number {
  if (y + needed > PAGE_BOTTOM) {
    doc.addPage();
    drawWatermark(doc);
    drawFooter(doc, docId);
    return 50;
  }
  return y;
}

// ── Main handler ───────────────────────────────────────────────────────────
export default function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const {
    medications,
    rawText,
    patientName,
    prescribingDoctor,
    prescriptionDate,
    clinicName,
    pharmacistNotes,
    caseId,
    generatedAt,
  } = req.body as {
    medications?: Array<{
      name: string; strength?: string; form?: string; frequency?: string;
      duration?: string; route?: string; quantity?: string; instructions?: string;
    }>;
    rawText?: string;
    patientName?: string;
    prescribingDoctor?: string;
    prescriptionDate?: string;
    clinicName?: string;
    pharmacistNotes?: string;
    caseId?: string;
    generatedAt?: string;
  };

  if ((!medications || medications.length === 0) && !rawText) {
    return res.status(400).json({ error: "No medication data provided" });
  }

  const docDate = prescriptionDate ||
    (generatedAt
      ? new Date(generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
      : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
  const docId = caseId || `MF-${Date.now().toString(36).toUpperCase()}`;
  const safePatientName = clean(patientName) || "Patient";
  const safeDoctor      = clean(prescribingDoctor) || "Not specified";
  const safeClinic      = clean(clinicName) || "";

  // ── If rawText is provided, render it directly in the PDF ─────────────────
  if (rawText && (!medications || medications.length === 0)) {
    const W2 = 612;
    const contentWidth2 = W2 - MARGIN * 2;
    const doc2 = new PDFDocument({
      size: "LETTER", margin: 0, autoFirstPage: true,
      info: {
        Title: `Medication Prescription Record — ${safePatientName}`,
        Author: "MediFlow AI",
        Subject: "Medication Prescription Record",
        Creator: "MediFlow AI Clinical Workflow Platform",
      },
    });
    const chunks2: Buffer[] = [];
    doc2.on("data", (chunk: Buffer) => chunks2.push(chunk));
    const pdfPromise2 = new Promise<void>((resolve) => {
      doc2.on("end", resolve);
      drawWatermark(doc2);
      drawFooter(doc2, docId);
      let y2 = drawHeader(doc2, safePatientName, safeDoctor, docDate, docId, safeClinic);
      // Important notice
      y2 = checkPage(doc2, y2, 36, docId);
      doc2.rect(MARGIN, y2, contentWidth2, 28).fill("#fef3c7");
      doc2.rect(MARGIN, y2, 3, 28).fill("#f59e0b");
      doc2.fontSize(7.5).fillColor("#92400e").font("Helvetica-Bold");
      doc2.text("IMPORTANT: ", MARGIN + 10, y2 + 9, { continued: true });
      doc2.font("Helvetica");
      doc2.text("This document is AI-assisted. Verify with a licensed pharmacist or clinician before dispensing.", { width: contentWidth2 - 80 });
      y2 += 38;
      // Section heading
      y2 = checkPage(doc2, y2, 40, docId);
      doc2.rect(MARGIN, y2, 3, 16).fill(TEAL);
      doc2.fontSize(10).fillColor(TEAL).font("Helvetica-Bold");
      doc2.text("PRESCRIBED MEDICATIONS", MARGIN + 10, y2 + 2);
      y2 += 28;
      // Render the AI output text line by line
      const lines = rawText.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) { y2 += 6; continue; }
        // Skip preamble/intro lines that are not medication entries
        const isPreamble = /^here is|^below is|^the following|^this is|^please find|^i have|^as requested/i.test(trimmed);
        if (isPreamble) continue;
        y2 = checkPage(doc2, y2, 16, docId);
        // Strip all markdown asterisks and formatting
        const displayLine = trimmed.replace(/\*\*/g, "").replace(/[*_`#]/g, "").trim();
        if (!displayLine) continue;
        // Bold headings: lines starting with a number like "1." or "1)"
        const isHeading = /^\d+[.):]/.test(displayLine);
        if (isHeading) {
          doc2.fontSize(9).fillColor(TEAL).font("Helvetica-Bold");
        } else {
          doc2.fontSize(8.5).fillColor(DARK_TEXT).font("Helvetica");
        }
        doc2.text(displayLine, MARGIN + (isHeading ? 0 : 12), y2, { width: contentWidth2 - 12 });
        y2 = doc2.y + 3;
      }
      doc2.end();
    });
    pdfPromise2.then(() => {
      const pdfBuffer2 = Buffer.concat(chunks2);
      const filename2 = `medication-record-${docId}.pdf`;
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${filename2}"`);
      res.setHeader("Content-Length", pdfBuffer2.length);
      res.status(200).send(pdfBuffer2);
    }).catch((err: Error) => {
      console.error("PDF generation error:", err);
      res.status(500).json({ error: "PDF generation failed" });
    });
    return;
  }

  // ── Sanitise medication data ─────────────────────────────────────────────
  // Extract pure drug name; keep other fields as-is (cleaned)
  const meds = (medications || []).map(m => ({
    name:         clean(m.name),
    strength:     clean(m.strength),
    form:         clean(m.form),
    route:        clean(m.route),
    frequency:    clean(m.frequency),
    duration:     clean(m.duration),
    quantity:     clean(m.quantity),
    instructions: clean(m.instructions),
  }));

  // ── Determine which columns actually have data ───────────────────────────
  // A column is shown only if at least one medication has a non-empty value for it.
  const hasStrength    = meds.some(m => m.strength);
  const hasForm        = meds.some(m => m.form);
  const hasRoute       = meds.some(m => m.route);
  const hasFrequency   = meds.some(m => m.frequency);
  const hasDuration    = meds.some(m => m.duration);
  const hasQuantity    = meds.some(m => m.quantity);
  const hasInstructions = meds.some(m => m.instructions);

  // Build active column list dynamically
  type ColDef = { key: string; label: string; w: number };
  const activeCols: ColDef[] = [
    { key: "num",      label: "#",         w: 22  },
    { key: "name",     label: "MEDICATION", w: 0   }, // flexible — fills remaining space
    ...(hasStrength  ? [{ key: "strength",  label: "DOSAGE",    w: 70  }] : []),
    ...(hasForm      ? [{ key: "form",      label: "FORM",      w: 55  }] : []),
    ...(hasRoute     ? [{ key: "route",     label: "ROUTE",     w: 50  }] : []),
    ...(hasFrequency ? [{ key: "frequency", label: "FREQUENCY", w: 95  }] : []),
    ...(hasDuration  ? [{ key: "duration",  label: "DURATION",  w: 50  }] : []),
    ...(hasQuantity  ? [{ key: "quantity",  label: "QTY",       w: 50  }] : []),
  ];

  const W = 612;
  const contentWidth = W - MARGIN * 2;

  // Calculate flexible name column width
  const fixedWidth = activeCols.reduce((sum, c) => sum + c.w, 0);
  const nameCol = activeCols.find(c => c.key === "name")!;
  nameCol.w = contentWidth - fixedWidth;

  // Assign x positions
  let xCursor = MARGIN;
  for (const col of activeCols) {
    (col as ColDef & { x: number }).x = xCursor;
    xCursor += col.w;
  }

  const doc = new PDFDocument({
    size: "LETTER", margin: 0, autoFirstPage: true,
    info: {
      Title: `Medication Prescription Record — ${safePatientName}`,
      Author: "MediFlow AI",
      Subject: "Medication Prescription Record",
      Creator: "MediFlow AI Clinical Workflow Platform",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const pdfPromise = new Promise<void>((resolve) => {
    doc.on("end", resolve);

    drawWatermark(doc);
    drawFooter(doc, docId);
    let y = drawHeader(doc, safePatientName, safeDoctor, docDate, docId, safeClinic);

    // ── Important notice ─────────────────────────────────────────────────
    y = checkPage(doc, y, 36, docId);
    doc.rect(MARGIN, y, contentWidth, 28).fill("#fef3c7");
    doc.rect(MARGIN, y, 3, 28).fill("#f59e0b");
    doc.fontSize(7.5).fillColor("#92400e").font("Helvetica-Bold");
    doc.text("IMPORTANT: ", MARGIN + 10, y + 9, { continued: true });
    doc.font("Helvetica");
    doc.text("This document is AI-assisted. Verify with a licensed pharmacist or clinician before dispensing.", { width: contentWidth - 80 });
    y += 38;

    // ── Section heading ──────────────────────────────────────────────────
    y = checkPage(doc, y, 40, docId);
    doc.rect(MARGIN, y, 3, 16).fill(TEAL);
    doc.fontSize(10).fillColor(TEAL).font("Helvetica-Bold");
    doc.text(
      `PRESCRIBED MEDICATIONS  (${meds.length} item${meds.length !== 1 ? "s" : ""})`,
      MARGIN + 10, y + 2
    );
    y += 24;

    // ── Table header row ─────────────────────────────────────────────────
    doc.rect(MARGIN, y, contentWidth, 18).fill(TEAL);
    doc.fontSize(7).fillColor("white").font("Helvetica-Bold");
    for (const col of activeCols as Array<ColDef & { x: number }>) {
      doc.text(col.label, col.x + 3, y + 5, { width: col.w - 4, lineBreak: false });
    }
    y += 18;

    // ── Data rows ────────────────────────────────────────────────────────
    for (const [idx, med] of meds.entries()) {
      const isAlt = idx % 2 === 1;

      // Estimate row height
      const freqLines  = med.frequency ? Math.ceil(med.frequency.length / 18) + 1 : 1;
      const nameLines  = Math.ceil(med.name.length / Math.max(nameCol.w / 6, 10)) + 1;
      const mainRowH   = Math.max(freqLines, nameLines) * 10 + 8;
      // Instructions row height: text at font-7.5 Helvetica, ~4.5px/char, 13pt line height.
      // Available text width = contentWidth - 90 (label 80px + 10px padding).
      const instrTextAvailWidth = contentWidth - 90;
      const instrCharsPerLine = Math.max(Math.floor(instrTextAvailWidth / 4.5), 8);
      const instrLines = med.instructions ? Math.ceil(med.instructions.length / instrCharsPerLine) : 0;
      const instrRowH  = instrLines > 0 ? instrLines * 13 + 14 : 0;
      const totalRowH  = mainRowH + instrRowH;

      y = checkPage(doc, y, totalRowH + 4, docId);

      // Row background
      doc.rect(MARGIN, y, contentWidth, totalRowH).fill(isAlt ? ROW_ALT : "white");

      // Vertical dividers
      doc.strokeColor(BORDER).lineWidth(0.3);
      for (const col of (activeCols as Array<ColDef & { x: number }>).slice(1)) {
        doc.moveTo(col.x, y).lineTo(col.x, y + totalRowH).stroke();
      }
      doc.moveTo(MARGIN + contentWidth, y).lineTo(MARGIN + contentWidth, y + totalRowH).stroke();

      const textY = y + 5;

      // Row number
      const numCol = activeCols.find(c => c.key === "num") as ColDef & { x: number };
      doc.fontSize(8).fillColor(TEAL).font("Helvetica-Bold");
      doc.text(`${idx + 1}`, numCol.x + 3, textY, { width: numCol.w - 4, lineBreak: false });

      // Medication name (bold, teal)
      const nameColFull = activeCols.find(c => c.key === "name") as ColDef & { x: number };
      doc.fontSize(8).fillColor(DARK_TEXT).font("Helvetica-Bold");
      doc.text(med.name || "Unknown", nameColFull.x + 3, textY, { width: nameColFull.w - 6 });

      // Other columns
      doc.fontSize(7.5).fillColor(DARK_TEXT).font("Helvetica");
      const fieldMap: Record<string, string> = {
        strength:  med.strength,
        form:      med.form,
        route:     med.route,
        frequency: med.frequency,
        duration:  med.duration,
        quantity:  med.quantity,
      };
      for (const col of activeCols as Array<ColDef & { x: number }>) {
        if (col.key === "num" || col.key === "name") continue;
        const val = fieldMap[col.key] || "—";
        const isFreq = col.key === "frequency";
        doc.text(val, col.x + 3, textY, { width: col.w - 4, lineBreak: isFreq });
      }

      // Instructions sub-row (amber tint, spans full width)
      // Use absolute X positions to avoid PDFKit cursor drift from continued:true
      if (med.instructions) {
        const instrY = y + mainRowH;
        doc.rect(MARGIN, instrY, contentWidth, instrRowH).fill("#fffbeb");
        doc.rect(MARGIN, instrY, 3, instrRowH).fill("#f59e0b"); // left accent stripe
        // Label — fixed position, no wrap
        doc.fontSize(7.5).fillColor("#92400e").font("Helvetica-Bold");
        doc.text("Instructions:", MARGIN + 8, instrY + 6, { width: 70, lineBreak: false });
        // Value — starts after label, full remaining width, wraps freely
        doc.fontSize(7.5).font("Helvetica").fillColor(DARK_TEXT);
        doc.text(med.instructions, MARGIN + 80, instrY + 6, { width: instrTextAvailWidth, lineBreak: true });
      }

      // Bottom border
      doc.moveTo(MARGIN, y + totalRowH).lineTo(MARGIN + contentWidth, y + totalRowH)
        .strokeColor(BORDER).lineWidth(0.3).stroke();
      y += totalRowH;
    }

    y += 16;

    // ── Pharmacist / Interaction Notes ───────────────────────────────────
    const safeNotes = clean(pharmacistNotes);
    if (safeNotes) {
      y = checkPage(doc, y, 50, docId);
      doc.rect(MARGIN, y, contentWidth, 16).fill(CORAL);
      doc.fontSize(8).fillColor("white").font("Helvetica-Bold");
      doc.text("PHARMACIST & INTERACTION NOTES", MARGIN + 8, y + 4);
      y += 22;
      doc.fontSize(8.5).fillColor(DARK_TEXT).font("Helvetica");
      doc.text(safeNotes, MARGIN + 8, y, { width: contentWidth - 16 });
      y = doc.y + 14;
    }

    // ── Patient instructions ─────────────────────────────────────────────
    y = checkPage(doc, y, 80, docId);
    doc.rect(MARGIN, y, 3, 16).fill(TEAL);
    doc.fontSize(9.5).fillColor(TEAL).font("Helvetica-Bold");
    doc.text("INSTRUCTIONS FOR THE PATIENT", MARGIN + 10, y + 2);
    y += 24;

    const instrList = [
      "Take all medications exactly as prescribed. Do not skip doses or stop early without consulting your doctor.",
      "If you miss a dose, take it as soon as you remember — unless it is almost time for the next dose. Never double up.",
      "Store medications as directed (room temperature, away from moisture and direct sunlight, unless otherwise stated).",
      "Report any unexpected side effects or allergic reactions (rash, swelling, difficulty breathing) to your doctor immediately.",
      "Do not share your medications with others. Keep all medicines out of reach of children.",
    ];
    for (const instr of instrList) {
      y = checkPage(doc, y, 20, docId);
      doc.fontSize(8).fillColor(DARK_TEXT).font("Helvetica");
      doc.text("•", MARGIN + 4, y, { width: 10, lineBreak: false });
      doc.text(instr, MARGIN + 16, y, { width: contentWidth - 20 });
      y = doc.y + 4;
    }

    y += 14;

    // ── Signature block ───────────────────────────────────────────────────
    y = checkPage(doc, y, 80, docId);
    doc.moveTo(MARGIN, y).lineTo(W - MARGIN, y).strokeColor(BORDER).lineWidth(0.5).stroke();
    y += 14;
    const sigW = 150;
    const sigGap = 26;
    const sigs = [
      { label: "Dispensing Pharmacist Signature", x: MARGIN },
      { label: "Date Dispensed",                  x: MARGIN + sigW + sigGap },
      { label: "Prescriber Verification",         x: MARGIN + (sigW + sigGap) * 2 },
    ];
    sigs.forEach(({ label, x }) => {
      doc.moveTo(x, y + 26).lineTo(x + sigW, y + 26).strokeColor(DARK_TEXT).lineWidth(0.4).stroke();
      doc.fontSize(7).fillColor(MID_GREY).font("Helvetica");
      doc.text(label, x, y + 30, { width: sigW, align: "center" });
    });

    doc.end();
  });

  pdfPromise.then(() => {
    const pdfBuffer = Buffer.concat(chunks);
    const filename = `medication-record-${docId}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", pdfBuffer.length);
    res.status(200).send(pdfBuffer);
  }).catch((err: Error) => {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "PDF generation failed" });
  });
}
